apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: 549079173707.dkr.ecr.us-east-1.amazonaws.com/webapp:latest
        ports:
        - containerPort: 81
        env:
        - name: DBHOST
          value: mysql
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: DBPWD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: DATABASE
          value: employees
        - name: S3_BUCKET
          valueFrom:
            configMapKeyRef:
              name: webapp-config
              key: S3_BUCKET
        - name: S3_KEY
          valueFrom:
            configMapKeyRef:
              name: webapp-config
              key: S3_KEY
        - name: GROUP_NAME
          valueFrom:
            configMapKeyRef:
              name: webapp-config
              key: GROUP_NAME
        - name: GROUP_SLOGAN
          valueFrom:
            configMapKeyRef:
              name: webapp-config
              key: GROUP_SLOGAN
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_SESSION_TOKEN
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: AWS_SESSION_TOKEN
        - name: AWS_REGION
          value: us-east-1
      imagePullSecrets:
      - name: ecr-secret
